### ISSUE TITLE
question

### ISSUE THREAD

**Issue by fujianhai** [SooLab/Plain-Det#2]
if I have 50/100 datasets, then I would need 50/100 heads, are there any more efficient methods available?

**Comment by ZhuYuChenNO1** [comment]
Hi @fujianhai , the 'head' in our paper is essentially just a `num_classes*hidden_dim`  matrix for each dataset, serving as the classifier for the model. In our experiments, we did not encounter any efficiency issues. Maybe you are looking for something like  `Unified classifier`? I hope the figure 2 in [UniDet](https://arxiv.org/pdf/2102.13086) can help you.

**Comment by fujianhai** [comment]
ok， thank you。
